# This rule is not used by the project kube-freeze-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the freeze-operator.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-freeze-operator
    app.kubernetes.io/managed-by: kustomize
  name: freezeexception-editor-role
rules:
- apiGroups:
  - freeze-operator.io
  resources:
  - freezeexceptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - freeze-operator.io
  resources:
  - freezeexceptions/status
  verbs:
  - get
