# This rule is not used by the project kube-freeze-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over freeze-operator.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-freeze-operator
    app.kubernetes.io/managed-by: kustomize
  name: maintenancewindow-admin-role
rules:
- apiGroups:
  - freeze-operator.io
  resources:
  - maintenancewindows
  verbs:
  - '*'
- apiGroups:
  - freeze-operator.io
  resources:
  - maintenancewindows/status
  verbs:
  - get
